const DataCard = [
    {
        title: 'Candi Borobudur',
        description: 'Candi Borobudur adalah candi Buddha terbesar di dunia. Candi ini berlokasi di Borobudur, Magelang, Jawa Tengah, Indonesia.',
        rating: 2,
        image: 'http://www.getsready.com/wp-content/uploads/2014/04/borobudur-2.jpg',
        city: 'Magelang',
        logo: 'https://2.bp.blogspot.com/-7niH8fmBHF4/XDL0PFp1sHI/AAAAAAAABvg/f_MOJEb9lJcxrfUbTTXA5Z5W5mNKXaSEQCLcBGAs/s1600/logo%2Bjateng.png',
        kategori: 'Budaya, Sejarah, Arsitektur',
    },
    {
        title: 'Candi Prambanan',
        description: 'Candi Prambanan adalah kompleks candi Hindu terbesar di Indonesia yang dibangun pada abad ke-9 masehi.',
        rating: 4,
        image: 'http://www.getsready.com/wp-content/uploads/2014/04/borobudur-2.jpg',
        city: 'Sleman',
        logo: 'https://2.bp.blogspot.com/-7niH8fmBHF4/XDL0PFp1sHI/AAAAAAAABvg/f_MOJEb9lJcxrfUbTTXA5Z5W5mNKXaSEQCLcBGAs/s1600/logo%2Bjateng.png',
        kategori: 'Budaya, Sejarah, Arsitektur',
    },
    {
        title: 'Candi Ratu Boko',
        description: 'Candi Ratu Boko adalah sebuah kompleks candi yang terletak di Desa Bokoharjo, Kecamatan Prambanan, Kabupaten Sleman, Daerah Istimewa Yogyakarta, Indonesia.',
        rating: 3.5,
        image: 'http://www.getsready.com/wp-content/uploads/2014/04/borobudur-2.jpg',
        city : 'Sleman',
        logo: 'https://2.bp.blogspot.com/-7niH8fmBHF4/XDL0PFp1sHI/AAAAAAAABvg/f_MOJEb9lJcxrfUbTTXA5Z5W5mNKXaSEQCLcBGAs/s1600/logo%2Bjateng.png',
        kategori: 'Budaya, Sejarah, Arsitektur',
    },
    {
        title: 'Candi Sambisari',
        description: 'Candi Sambisari adalah sebuah candi Hindu yang terletak di Desa Purwomartani, Kalasan, Sleman, Yogyakarta, Indonesia.',
        rating: 4.5,
        image: 'http://www.getsready.com/wp-content/uploads/2014/04/borobudur-2.jpg',
        city : 'Sleman',
        logo: 'https://2.bp.blogspot.com/-7niH8fmBHF4/XDL0PFp1sHI/AAAAAAAABvg/f_MOJEb9lJcxrfUbTTXA5Z5W5mNKXaSEQCLcBGAs/s1600/logo%2Bjateng.png',
        kategori: 'Budaya, Sejarah, Arsitektur',
    },    {
        title: 'Candi Sambisari',
        description: 'Candi Sambisari adalah sebuah candi Hindu yang terletak di Desa Purwomartani, Kalasan, Sleman, Yogyakarta, Indonesia.',
        rating: 4.5,
        image: 'http://www.getsready.com/wp-content/uploads/2014/04/borobudur-2.jpg',
        city : 'Sleman',
        logo: 'https://2.bp.blogspot.com/-7niH8fmBHF4/XDL0PFp1sHI/AAAAAAAABvg/f_MOJEb9lJcxrfUbTTXA5Z5W5mNKXaSEQCLcBGAs/s1600/logo%2Bjateng.png',
        kategori: 'Budaya, Sejarah, Arsitektur',
    },    {
        title: 'Candi Sambisari',
        description: 'Candi Sambisari adalah sebuah candi Hindu yang terletak di Desa Purwomartani, Kalasan, Sleman, Yogyakarta, Indonesia.',
        rating: 4.5,
        image: 'http://www.getsready.com/wp-content/uploads/2014/04/borobudur-2.jpg',
        city : 'Sleman',
        logo: 'https://2.bp.blogspot.com/-7niH8fmBHF4/XDL0PFp1sHI/AAAAAAAABvg/f_MOJEb9lJcxrfUbTTXA5Z5W5mNKXaSEQCLcBGAs/s1600/logo%2Bjateng.png',
        kategori: 'Budaya, Sejarah, Arsitektur',
    },    {
        title: 'Candi Sambisari',
        description: 'Candi Sambisari adalah sebuah candi Hindu yang terletak di Desa Purwomartani, Kalasan, Sleman, Yogyakarta, Indonesia.',
        rating: 4.5,
        image: 'http://www.getsready.com/wp-content/uploads/2014/04/borobudur-2.jpg',
        city : 'Sleman',
        logo: 'https://2.bp.blogspot.com/-7niH8fmBHF4/XDL0PFp1sHI/AAAAAAAABvg/f_MOJEb9lJcxrfUbTTXA5Z5W5mNKXaSEQCLcBGAs/s1600/logo%2Bjateng.png',
        kategori: 'Budaya, Sejarah, Arsitektur',
    },
    {
        title: 'Pantai Parangtritis',
        description: 'Pantai Parangtritis adalah sebuah pantai yang terletak di Kecamatan Kretek, Kabupaten Bantul, Yogyakarta, Indonesia.',
        rating: 1.5,
        image: 'http://www.getsready.com/wp-content/uploads/2014/04/borobudur-2.jpg',
        city: 'Bantul',
        logo: 'https://2.bp.blogspot.com/-7niH8fmBHF4/XDL0PFp1sHI/AAAAAAAABvg/f_MOJEb9lJcxrfUbTTXA5Z5W5mNKXaSEQCLcBGAs/s1600/logo%2Bjateng.png',
        kategori: 'Budaya, Sejarah, Arsitektur',
    }
]

export default DataCard;